<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DhErrorLogging\Module'                                           => __DIR__ . '/Module.php',
  'DhErrorLogging\Factory\Generator\ErrorReferenceGeneratorFactory' => __DIR__ . '/src/DhErrorLogging/Factory/Generator/ErrorReferenceGeneratorFactory.php',
  'DhErrorLogging\Factory\Logger\LoggerFactory'                     => __DIR__ . '/src/DhErrorLogging/Factory/Logger/LoggerFactory.php',
  'DhErrorLogging\Factory\Processor\ExtrasProcessorFactory'         => __DIR__ . '/src/DhErrorLogging/Factory/Processor/ExtrasProcessorFactory.php',
  'DhErrorLogging\Factory\Writer\DbWriterFactory'                   => __DIR__ . '/src/DhErrorLogging/Factory/Writer/DbWriterFactory.php',
  'DhErrorLogging\Generator\ErrorReference'                         => __DIR__ . '/src/DhErrorLogging/Generator/ErrorReference.php',
  'DhErrorLogging\Generator\ErrorReferenceInterface'                => __DIR__ . '/src/DhErrorLogging/Generator/ErrorReferenceInterface.php',
  'DhErrorLogging\Processor\Extras'                                 => __DIR__ . '/src/DhErrorLogging/Processor/Extras.php',
);
